version: '3.8'

services:
  prod_db:
    user: prod
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data/
    networks:
      - prod_network

  prod_backend:
    user: prod
    container_name: backend
    build: ./backend
    command: /start_prod.sh
    volumes:
      - ./backend:/code
      - prod_django-static:/code/static
    ports:
      - "8000:8000"
    networks:
      - prod_network
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DJANGO_SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DJANGO_ALLOWED_HOSTS

  prod_nginx:
    user: prod
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/prod/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/prod/prod.conf:/etc/nginx/nginx.conf:ro
      - prod_django-static:/usr/src/app/static
    networks:
      -  prod_network

networks:
  prod_network:
    driver: bridge

volumes:
  prod_django-static:
  prod_postgres_data:
