version: '3.8'

services:
  db:
    container_name: db
    image: postgres:alpine
    env_file:
      - ./.env.dev
    networks:
      - main
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build: ./backend
    command: /start_dev.sh
    env_file:
      - ./.env.dev
    volumes:
      - ./backend:/code
      - django-static:/code/static
    ports:
      - "9000:8000"
    networks:
      - main
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
    ports:
      - "9090:8080"
    networks:
      - main
    depends_on:
      - backend
      - db
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/dev/Dockerfile
    ports:
      - "90:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - django-static:/usr/src/app/static
    networks:
      -  main

networks:
  main:
    driver: bridge

volumes:
  django-static:
