version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - main

  backend:
    container_name: backend
    build: ./backend
    command: /start_prod.sh
    volumes:
      - ./backend:/code
      - django-static:/code/static
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DJANGO_SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DJANGO_ALLOWED_HOSTS

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/prod/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/prod/prod.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    networks:
      -  main

networks:
  main:
    driver: bridge

volumes:
  django-static:
  postgres_data:
