name: production build

on:
  push:
    branches: [ master ]


jobs:
  pull_and_start:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose stack
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        run: docker-compose -f docker-compose.prod.yml up --build -d
      - name: Check running containers
        run: docker ps -a
      - name: Check prod_backend logs
        run: docker logs backend
      - name: Check prod_nginx and prod_frontend logs
        run: docker logs nginx
      - name: Check db logs
        run: docker logs db
